<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html>

<head>

<meta http-equiv="Content-Language" content="en-us">

<title>Hybrid Electric Car - PlanetTran</title>

<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">

<link href="planettran.css" rel="stylesheet" type="text/css">

<meta name="description" content="Boston and San Francisco based PlanetTran, utilizing a fleet of Hybrid Electric Cars to provide fuel efficient transportation to individuals and organizations.">

<meta name="keywords" content="Hybrid Electric Car, Boston Hybrid Electric Car, San Francisco Hybrid Electric Car, Boston Car Service, Car Service Boston, San Francisco Car Service, Car Service San Francisco">

</head>

<body leftmargin="0" topmargin="10" marginwidth="0" marginheight="0">

<div align="center">

  <table width="600" border="0" cellpadding="0" cellspacing="0">
<?php include("header_nav.shtml"); ?>	
    <tr> 
      <td colspan="4">
      
 
 <div id="main-content">
	<h2 class="page-header"><img border="0" alt="Hybrid Vehicles" src="images/header_hybridvehicles.gif" width="578" height="47" /></h2>
	<h3 class="page-subheader">Hybrid Electric Cars</h3>
	<div class="article">
		
		<dl class="faqs">
			<dt>What is a hybrid car? </dt>
				<dd>
					<p>A hybrid car is so-named because it has dual power sources for providing mechanical energy to the car's drive train.  It utilizes both a familiar gasoline fueled internal combustion engine AND an electric motor with a battery for electricity storage.</p>
				</dd>
			<dt>How does a hybrid car work?</dt>
				<dd>
					<p>Generally, hybrid cars can use both sources of mechanical energy (electric motor and gas engines) to power the drivetrain.  'Pure' hybrids, like the Toyota Prius, are fundamentally electric cars with a gas engine onboard to serve as an electricity generator to charge the battery.  The gas engine can also power the drive train directly like a non-hybrid vehicle, when power is required.  When the hybrid is stopped in traffic, or 'idling', the engine will shut off.  The car can even be driven at low speeds/acceleration using the electric motor alone!  The upshot is that hybrids are very fuel efficient because they turn the gas engine off when it is not needed.</p>
				</dd>
			<dt>Do you have to plug them in?</dt>
				<dd>
					<p>No.  The electricity stored in the battery is generated by the gas engine and the braking mechanism.  Incidentally, manufacturers are working on hybrids with higher capacity batteries which can be 'plugged in', like the first electric cars, which have unlimited range because of the gas engine.</p>
				</dd>
			<dt>What is regenerative braking?</dt>
				<dd>
					<p>Regenerative braking is a technological advance that hybrids employ which uses the electric motor to slow the car down. One of the most inefficient things one can do in a vehicle is stop it.  The energy associated with the car being in motion must be dissipated as heat on the brakes in order for the car to stop.  Cars with regenerative braking use the resistance of the electric motor to slow the car, while generating electricity which can be stored in the battery.  This wonderfully efficient braking mechanism actually enables the car to use less gas when driving around city streets than when it's traveling at highway speeds. There is no new physics involved, only that there has never been a battery on-board a car to store such 'regenerated' electricity, but now there is on hybrids.</p> 
				</dd>
		</dl>
			
	</div>
</div>	


		</td>
    </tr>
	<?php include("footer.shtml"); ?>
  </table>

</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-6290296-1");
pageTracker._trackPageview();
</script>
</body>

</html>
